services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.reactUI
    ports:
      - "3000:3000"   
    depends_on:
      - db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "9000:9000"   
    depends_on:
      - db
  db:
    volumes:
      - app_db:/data/db
    image: mongo:latest
    ports:
      - "80:80" 
volumes:
   app_db: