FROM node:16

WORKDIR /app

COPY ./package.json ./package.json
COPY ./.env ./.env
COPY ./config ./config
COPY ./models ./models
COPY ./routes ./routes
COPY ./server.js ./server.js

RUN yarn install

EXPOSE 9000

CMD ["node", "server.js"]